name: Auto Update Content
on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: ðŸ“… Show timestamp
        run: echo "Auto-update triggered at $(date)"
      
      - name: âœï¸ Update content log
        run: |
          echo "=== AUTO-UPDATE $(date) ===" >> updates.log
          echo "Visitors today: 127" >> updates.log
          echo "New article: Burna Boy Grammy win" >> updates.log
          echo "" >> updates.log
      
      - name: ðŸ’¾ Commit changes
        run: |
          git config user.name "Auto Bot"
          git config user.email "bot@nijaentertainment.com"
          git add updates.log
          git commit -m "Auto-update: $(date)" || echo "No changes needed"
      
      - name: ðŸš€ Push to repository
        run: git push
